# Generated by Django 5.1.4 on 2024-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField()),
                ('entrevistado', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entrevistas/')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
