# Generated by Django 5.1.4 on 2024-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_entrevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
