# Generated by Django 5.1.4 on 2024-12-30 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_categoria_alter_post_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
