# Generated by Django 5.1.4 on 2025-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_creado_post_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='analisis/')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
