# Generated by Django 5.1.4 on 2025-01-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='is_read',
        ),
    ]
