# Generated by Django 5.1.4 on 2025-01-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
    ]
